site_name: Wayne's blogs
site_url: https://q1ucheng.github.io/blogs/
site_author: Wayne

# Repository, ç”¨äºç”Ÿæˆå³ä¸Šè§’çš„ä»“åº“é“¾æ¥
repo_name: Q1ucheng/blogs
repo_url: https://github.com/Q1ucheng/blogs

theme:
  icon:
    repo: fontawesome/brands/github    # æ›´æ”¹å³ä¸Šè§’ä»“åº“å›¾æ ‡
    logo: material/marker              # æ›´æ”¹å·¦ä¸Šè§’ç½‘ç«™logo(markeræ˜¯ä¸€æ”¯é’¢ç¬”)
    # admonition:
    #   <type>: <icon> 
  name: material
  features:
    - navigation.top   # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - admonition
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.follow
    - content.tabs.link
    - content.code.copy
    - content.code.select
  highlightjs: true
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: cyan
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: indigo
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - CS61A:
    - introduction: Note/CS61A/1.CS61A_Structure_and_Interpretation_of_Computer_Programs.md
    - Functions: Note/CS61A/2.Functions.md
    - Control: Note/CS61A/3.Control.md
    - Higher-Order Function: Note/CS61A/4.Higher-Order_function.md
    - Environments: Note/CS61A/5.Environments.md
    - Function example: Note/CS61A/6.Function_example.md
    - Recursive Function: Note/CS61A/7.Recursive_function.md
    - Tree Recursion: Note/CS61A/8.Tree_recursion.md
    - Containers:  Note/CS61A/9.Containers.md
    - Data abstraction: Note/CS61A/10.Data_abstraction.md
    - Trees: Note/CS61A/11.Trees.md
    - Mutable Values: Note/CS61A/12.Mutable_values.md
    - HW03: Note/CS61A/HW03.md
    - Mutable Function: Note/CS61A/13.Mutable_functions.md
    - Iterators: Note/CS61A/14.Iterators.md
    - Object: Note/CS61A/15.Object.md
    - HW04: Note/CS61A/HW04.md
    - Inheritance: Note/CS61A/16.Inheritance.md 
    - Project Ants: Note/CS61A/Ants.md
    - Representation: Note/CS61A/17.Representation.md
    - Composition: Note/CS61A/18.Composition.md
    - Efficiency: Note/CS61A/19.Efficiency.md 
    - Lab08's Option Problems: Note/CS61A/Lab08's_Optional_Problems.md
    - Decomposition & Data example: Note/CS61A/20.Decomposition.md
    - Scheme: Note/CS61A/21.Scheme.md
    - Calculation: Note/CS61A/22.Calculation.md
    - Interpreters: Note/CS61A/23.Interpreters.md
    - scals.zip: Note/CS61A/24.Schemeéƒ¨åˆ†æ€»å’Œ.md
    - Lab11 & Scheme Project: Note/CS61A/25.Lab11.md
    - Declarative Programming: Note/CS61A/26.Declarative_Programming.md
    - Tables: Note/CS61A/27.Tables.md
    - Aggregation: Note/CS61A/28.Aggregation.md
    - Database(optional): Note/CS61A/29.Database.md
    - Tail Calls(optional): Note/CS61A/30.Tail_Calls.md
    - Macros(optional): Note/CS61A/31.Macros.md
    - Final Example: Note/CS61A/32.Final_Example.md
    - ConclusionsğŸ‰: Note/CS61A/Conclusions.md
  - Note: 
    # - CS61A Fall20:
    #   - introduction: Note/CS61A/1. CS61A Structure and Interpretation of Computer Programs.md
    #   - Functions: Note/CS61A/2. Functions.md
    #   - Control: Note/CS61A/3. Control.md
    #   - Higher-Order Function: Note/CS61A/4. Higher-Order Function.md
    #   - Environments: Note/CS61A/5. Environments.md
    #   - Function example: Note/CS61A/6. Function example.md
    #   - Recursive Function: Note/CS61A/7. Recursive Function.md
    #   - Tree Recursion: Note/CS61A/8. Tree Recursion.md
    #   - Containers:  Note/CS61A/9. Containers.md
    #   - Data abstraction: Note/CS61A/10. Data abstraction.md
    #   - Trees: Note/CS61A/11. Trees.md
    #   - Mutable Values: Note/CS61A/12. Mutable Values.md
    - Git & Github & GitLab: 
      - Git: Note/Git related/Git.md
      - Github: Note/Git related/Github.md 
    - MySQL:
      - è®°å½•å­¦ä¹ ä½¿ç”¨MySQLçš„è¿‡ç¨‹: Note/MySQL/Mysql_learning.md
    - PyQt6 & PySide6:
      - PyQt6/PySide6: Note/PyQt6&PySide6/PyQt6PySide6.md
    - Numerical analysis:
      - è®¡ç®—æ–¹æ³•ç¬¬äºŒç« : Note/Numerical analysis/è®¡ç®—æ–¹æ³•ç¬¬äºŒç« .md
      - NPUCM2024: Note/Numerical analysis/è®°å½•.md
    - LaTeX related:
      - æ•°å­¦å»ºæ¨¡ä¸­çš„LaTeXä»£ç : Note/LaTeX related/æ•°å­¦å»ºæ¨¡ä¸­çš„LaTeXä»£ç .md
    - Markdown related:
      - ä¸€äº›Markdownçš„ç”¨æ³•: Note/Markdown related/practice.md
    - MkDocs-material:
      - MkDocséƒ¨ç½²é…ç½®ä¸­errorçš„è§£å†³: Note/Mkdocs-material/mkdocséƒ¨ç½²é…ç½®ä¸­errorçš„è§£å†³.md
      - è®¾è®¡MkDocs: Note/Mkdocs-material/mkdocsè®¾è®¡.md
      - å°è¯•ç”¨HTML+CSSå®ç°é¦–é¡µæ‰“å­—æ•ˆæœæ¸²æŸ“: Note/Mkdocs-material/ç”¨HTML+CSSå®ç°é¦–é¡µæ‰“å­—æ•ˆæœæ¸²æŸ“.md
  - Blog: Blog/Blog.md
    
extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  # - javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# extra_css:
#   - stylesheets/extra.css
#   - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
#   - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  generator: false  #åˆ é™¤é¡µè„šæ˜¾ç¤ºâ€œä½¿ç”¨ MkDocs ææ–™åˆ¶é€ â€
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Q1ucheng
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/2001723051?spm_id_from=333.1007.0.0
    - icon: fontawesome/solid/paper-plane
      link: https://ronaldln.github.io/MyPamphlet/
  alternate:
    - name: English(åŠŸèƒ½æœªå¼€æ”¾)
      link: /en/ 
      lang: en
    - name: Chinese(åŠŸèƒ½æœªå¼€æ”¾)
      link: /zh/
      lang: zh

extra_css:
  - stylesheets/extra.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css


markdown_extensions:
  - admonition  # æ­¤é…ç½®å¯ç”¨å‘Šè¯«ï¼Œå…è®¸ä½¿å®ƒä»¬å¯æŠ˜å ï¼Œå¹¶å…è®¸åœ¨å‘Šè¯«ä¸­åµŒå¥—ä»»æ„å†…å®¹
  - pymdownx.details  # æ­¤é…ç½®å¯ç”¨å‘Šè¯«ï¼Œå…è®¸ä½¿å®ƒä»¬å¯æŠ˜å ï¼Œå¹¶å…è®¸åœ¨å‘Šè¯«ä¸­åµŒå¥—ä»»æ„å†…å®¹
  - pymdownx.superfences:  # æ­¤é…ç½®å¯ç”¨å‘Šè¯«ï¼Œå…è®¸ä½¿å®ƒä»¬å¯æŠ˜å ï¼Œå¹¶å…è®¸åœ¨å‘Šè¯«ä¸­åµŒå¥—ä»»æ„å†…å®¹
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - meta # æ”¯æŒMarkdownæ–‡ä»¶ä¸Šæ–¹è‡ªå®šä¹‰æ ‡é¢˜æ ‡ç­¾ç­‰
  - pymdownx.arithmatex:  # latexæ”¯æŒ
      generic: true
  - toc:
      permalink: true # å›ºå®šæ ‡é¢˜ä½ç½®ä¸ºå½“å‰ä½ç½®
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      anchor_linenums: true
      linenums: true # æ˜¾ç¤ºè¡Œå·
      auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.critic  # çªå‡ºæ˜¾ç¤ºæ–‡æ¡£çš„å„ä¸ªéƒ¨åˆ†æˆ–åº”ç”¨ç‰¹å®šæ ¼å¼
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: Copyright &copy; 2023 Wayne # å·¦ä¸‹è§’çš„ç‰ˆæƒå£°æ˜

plugins:
  - search:
      lang:
        - en
        - zh
  - git-revision-date-localized:
      enable_creation_date: true
